import React, { useState } from 'react';
// @ts-ignore
import outputs from '../../amplify_outputs.json';

interface CheckoutButtonProps {
    items: any[];
    customerEmail?: string;
    shippingAddress?: any;
    userId?: string;
}

export const CheckoutButton: React.FC<CheckoutButtonProps> = ({ items, customerEmail, shippingAddress, userId }) => {
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const handleCheckout = async () => {
        setLoading(true);
        setError(null);

        try {
            // Get the function URL from local outputs config (generated by ampx sandbox)
            const functionUrl = outputs.custom?.createCheckoutSessionUrl;

            if (!functionUrl) {
                throw new Error('Endpoint de pago no configurado en outputs.');
            }

            const response = await fetch(functionUrl, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ items, customerEmail, shippingAddress, userId }),
            });

            const data = await response.json();

            if (!response.ok) {
                throw new Error(data.error || 'Error al iniciar el pago.');
            }

            if (data.url) {
                window.location.href = data.url;
            }
        } catch (err: any) {
            console.error(err);
            setError(err.message);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className='flex flex-col gap-2'>
            {error && <p className="text-red-500 text-sm">{error}</p>}
            <button
                onClick={handleCheckout}
                disabled={loading || items.length === 0}
                className={`w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 px-6 rounded-lg transition-colors ${loading ? 'opacity-50 cursor-not-allowed' : ''}`}
            >
                {loading ? 'Procesando...' : 'Iniciar Pago con Pagar'}
            </button>
        </div>
    );
};
